//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSH.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BPMServices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BPMServices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSH.Core.Resources.BPMServices", typeof(BPMServices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPL.
        /// </summary>
        internal static string SrvCode_Appeal {
            get {
                return ResourceManager.GetString("SrvCode_Appeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QAPPENQ.
        /// </summary>
        internal static string SrvCode_ApplicationEnquiry {
            get {
                return ResourceManager.GetString("SrvCode_ApplicationEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRTAPTMT.
        /// </summary>
        internal static string SrvCode_CreateAppointment {
            get {
                return ResourceManager.GetString("SrvCode_CreateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GALAPS.
        /// </summary>
        internal static string SrvCode_GetAllApplication {
            get {
                return ResourceManager.GetString("SrvCode_GetAllApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QGTALAPP.
        /// </summary>
        internal static string SrvCode_GetAllAppointments {
            get {
                return ResourceManager.GetString("SrvCode_GetAllAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCOFRS.
        /// </summary>
        internal static string SrvCode_GetCustomerOffer {
            get {
                return ResourceManager.GetString("SrvCode_GetCustomerOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDCMNTS.
        /// </summary>
        internal static string SrvCode_GetDocuments {
            get {
                return ResourceManager.GetString("SrvCode_GetDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP.
        /// </summary>
        internal static string SrvCode_OTP {
            get {
                return ResourceManager.GetString("SrvCode_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAPPDTLS.
        /// </summary>
        internal static string SrvCode_SaveApplication {
            get {
                return ResourceManager.GetString("SrvCode_SaveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDAPP.
        /// </summary>
        internal static string SrvCode_UpdateAppointment {
            get {
                return ResourceManager.GetString("SrvCode_UpdateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLDCSP.
        /// </summary>
        internal static string SrvCode_ValidateCustomerSelectedProduct {
            get {
                return ResourceManager.GetString("SrvCode_ValidateCustomerSelectedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appeal.
        /// </summary>
        internal static string SrvName_Appeal {
            get {
                return ResourceManager.GetString("SrvName_Appeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationEnquiry.
        /// </summary>
        internal static string SrvName_ApplicationEnquiry {
            get {
                return ResourceManager.GetString("SrvName_ApplicationEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateAppointment.
        /// </summary>
        internal static string SrvName_CreateAppointment {
            get {
                return ResourceManager.GetString("SrvName_CreateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllApplication.
        /// </summary>
        internal static string SrvName_GetAllApplication {
            get {
                return ResourceManager.GetString("SrvName_GetAllApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllAppointments.
        /// </summary>
        internal static string SrvName_GetAllAppointments {
            get {
                return ResourceManager.GetString("SrvName_GetAllAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCustomerOffer.
        /// </summary>
        internal static string SrvName_GetCustomerOffer {
            get {
                return ResourceManager.GetString("SrvName_GetCustomerOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetDocuments.
        /// </summary>
        internal static string SrvName_GetDocuments {
            get {
                return ResourceManager.GetString("SrvName_GetDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP.
        /// </summary>
        internal static string SrvName_OTP {
            get {
                return ResourceManager.GetString("SrvName_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveApplication.
        /// </summary>
        internal static string SrvName_SaveApplication {
            get {
                return ResourceManager.GetString("SrvName_SaveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateAppointment.
        /// </summary>
        internal static string SrvName_UpdateAppointment {
            get {
                return ResourceManager.GetString("SrvName_UpdateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateCustSe.
        /// </summary>
        internal static string SrvName_ValidateCustomerSelectedProduct {
            get {
                return ResourceManager.GetString("SrvName_ValidateCustomerSelectedProduct", resourceCulture);
            }
        }
    }
}
