//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSH.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSH.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not found..
        /// </summary>
        internal static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        internal static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists or empty..
        /// </summary>
        internal static string AlreadyExistOrEmpty {
            get {
                return ResourceManager.GetString("AlreadyExistOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string ApplicationApproved {
            get {
                return ResourceManager.GetString("ApplicationApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exsits.
        /// </summary>
        internal static string ApplicationExsits {
            get {
                return ResourceManager.GetString("ApplicationExsits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoftReject.
        /// </summary>
        internal static string ApplicationRefer {
            get {
                return ResourceManager.GetString("ApplicationRefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HardReject.
        /// </summary>
        internal static string ApplicationReject {
            get {
                return ResourceManager.GetString("ApplicationReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM Error: {0}.
        /// </summary>
        internal static string BPMError {
            get {
                return ResourceManager.GetString("BPMError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Request failed!.
        /// </summary>
        internal static string ChangeRequestFailed {
            get {
                return ResourceManager.GetString("ChangeRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Report created successfully.
        /// </summary>
        internal static string CsvReportCreated {
            get {
                return ResourceManager.GetString("CsvReportCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Report creation failed.
        /// </summary>
        internal static string CsvReportCreationFailed {
            get {
                return ResourceManager.GetString("CsvReportCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to an error, data could not be deleted..
        /// </summary>
        internal static string DataDeleteFailed {
            get {
                return ResourceManager.GetString("DataDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to an error, data could not be added..
        /// </summary>
        internal static string DataInsertFailed {
            get {
                return ResourceManager.GetString("DataInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to an error, data could not be updated..
        /// </summary>
        internal static string DataUpdateFailed {
            get {
                return ResourceManager.GetString("DataUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date Format.
        /// </summary>
        internal static string DateInvalidDate {
            get {
                return ResourceManager.GetString("DateInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DateTime Format.
        /// </summary>
        internal static string DateInvalidDateTime {
            get {
                return ResourceManager.GetString("DateInvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted successfully!.
        /// </summary>
        internal static string DeletedSuccess {
            get {
                return ResourceManager.GetString("DeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your device is Inactive please contact administrator.
        /// </summary>
        internal static string DeviceInActive {
            get {
                return ResourceManager.GetString("DeviceInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inserted successfully!.
        /// </summary>
        internal static string InsertedSuccess {
            get {
                return ResourceManager.GetString("InsertedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Attendance Found.
        /// </summary>
        internal static string InvalidAttendance {
            get {
                return ResourceManager.GetString("InvalidAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid LOV group..
        /// </summary>
        internal static string InvalidLOVGroup {
            get {
                return ResourceManager.GetString("InvalidLOVGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid..
        /// </summary>
        internal static string InvalidObject {
            get {
                return ResourceManager.GetString("InvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid permission..
        /// </summary>
        internal static string InvalidPermission {
            get {
                return ResourceManager.GetString("InvalidPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid report..
        /// </summary>
        internal static string InvalidReport {
            get {
                return ResourceManager.GetString("InvalidReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOV with same key or value already exists..
        /// </summary>
        internal static string LOVExists {
            get {
                return ResourceManager.GetString("LOVExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content found!.
        /// </summary>
        internal static string NoContent {
            get {
                return ResourceManager.GetString("NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found!.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        internal static string ObjectRequired {
            get {
                return ResourceManager.GetString("ObjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect OTP, please enter correct value..
        /// </summary>
        internal static string OneTimePinInvalid {
            get {
                return ResourceManager.GetString("OneTimePinInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Pin should be 4 characters long.
        /// </summary>
        internal static string OneTimePinLength {
            get {
                return ResourceManager.GetString("OneTimePinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide one time pin value.
        /// </summary>
        internal static string OneTimePinRequired {
            get {
                return ResourceManager.GetString("OneTimePinRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OTP has expired. Check your email or SMS for the updated OTP..
        /// </summary>
        internal static string OneTimePinSentToEmail {
            get {
                return ResourceManager.GetString("OneTimePinSentToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP varification is succeded.
        /// </summary>
        internal static string OneTimePinVerified {
            get {
                return ResourceManager.GetString("OneTimePinVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll cannot be processed for current date..
        /// </summary>
        internal static string PayrollCurrentDateError {
            get {
                return ResourceManager.GetString("PayrollCurrentDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Report created successfully.
        /// </summary>
        internal static string PdfReportCreated {
            get {
                return ResourceManager.GetString("PdfReportCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Report creation failed.
        /// </summary>
        internal static string PdfReportCreationFailed {
            get {
                return ResourceManager.GetString("PdfReportCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} records deleted!.
        /// </summary>
        internal static string RecordsDeleted {
            get {
                return ResourceManager.GetString("RecordsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} records updated!.
        /// </summary>
        internal static string RecordsUpdated {
            get {
                return ResourceManager.GetString("RecordsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another hierarchy found.
        /// </summary>
        internal static string RegionalHierarchyFound {
            get {
                return ResourceManager.GetString("RegionalHierarchyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hierarchy found.
        /// </summary>
        internal static string RegionalHierarchyInvalid {
            get {
                return ResourceManager.GetString("RegionalHierarchyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized. User does not exists in your Hierarchy.
        /// </summary>
        internal static string RegionalHierarchyUnauthorized {
            get {
                return ResourceManager.GetString("RegionalHierarchyUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required data is missing.
        /// </summary>
        internal static string RequiredData {
            get {
                return ResourceManager.GetString("RequiredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent mail not found..
        /// </summary>
        internal static string SentMailNotFound {
            get {
                return ResourceManager.GetString("SentMailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        internal static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Result.
        /// </summary>
        internal static string SuccessResult {
            get {
                return ResourceManager.GetString("SuccessResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorize to perform this operation..
        /// </summary>
        internal static string UnAuthrized {
            get {
                return ResourceManager.GetString("UnAuthrized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is un changed!.
        /// </summary>
        internal static string UnChanged {
            get {
                return ResourceManager.GetString("UnChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated successfully!.
        /// </summary>
        internal static string UpdatedSuccess {
            get {
                return ResourceManager.GetString("UpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked. Please contact super admin.
        /// </summary>
        internal static string UserAccountLocked {
            get {
                return ResourceManager.GetString("UserAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account doesn&apos;t exist.
        /// </summary>
        internal static string UserAccountNotExist {
            get {
                return ResourceManager.GetString("UserAccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account doesn’t exist. Kindly register a new account.
        /// </summary>
        internal static string UserAccountNotExistCreateNew {
            get {
                return ResourceManager.GetString("UserAccountNotExistCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists..
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password assign successfully.
        /// </summary>
        internal static string UserAssignPasswordSuccessfully {
            get {
                return ResourceManager.GetString("UserAssignPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been blocked. Please contact HR.
        /// </summary>
        internal static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been deleted. Please contact your administrator.
        /// </summary>
        internal static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User did not confirm email..
        /// </summary>
        internal static string UserEmailNotConfirm {
            get {
                return ResourceManager.GetString("UserEmailNotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alphabetic characters are allowed in firstname and lastname fields.
        /// </summary>
        internal static string UserFirstAndLastName {
            get {
                return ResourceManager.GetString("UserFirstAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is Inactive please contact administrator.
        /// </summary>
        internal static string UserFreeze {
            get {
                return ResourceManager.GetString("UserFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is Inactive please contact administrator.
        /// </summary>
        internal static string UserInActivation {
            get {
                return ResourceManager.GetString("UserInActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is inactive..
        /// </summary>
        internal static string UserInactive {
            get {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect old password.
        /// </summary>
        internal static string UserIncorrectOldPassword {
            get {
                return ResourceManager.GetString("UserIncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email address..
        /// </summary>
        internal static string UserInvalidEmail {
            get {
                return ResourceManager.GetString("UserInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string UserInvalidPassword {
            get {
                return ResourceManager.GetString("UserInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Role..
        /// </summary>
        internal static string UserInvalidRole {
            get {
                return ResourceManager.GetString("UserInvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token.
        /// </summary>
        internal static string UserInvalidToken {
            get {
                return ResourceManager.GetString("UserInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        internal static string UserInvalidUser {
            get {
                return ResourceManager.GetString("UserInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        internal static string UserInvalidUserName {
            get {
                return ResourceManager.GetString("UserInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or IMEI number is incorrect.
        /// </summary>
        internal static string UserInvalidUserNameOrImeiNumber {
            get {
                return ResourceManager.GetString("UserInvalidUserNameOrImeiNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email/mobile number or password is incorrect.
        /// </summary>
        internal static string UserInvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("UserInvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid_Grant.
        /// </summary>
        internal static string UserIvalidGrant {
            get {
                return ResourceManager.GetString("UserIvalidGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName Already Exists.
        /// </summary>
        internal static string UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and old password must not be same.
        /// </summary>
        internal static string UserNewPasswordAndOldPasswordMatch {
            get {
                return ResourceManager.GetString("UserNewPasswordAndOldPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change successfully.
        /// </summary>
        internal static string UserPasswordChangeSuccessfully {
            get {
                return ResourceManager.GetString("UserPasswordChangeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be 6 characters long.
        /// </summary>
        internal static string UserPasswordLength {
            get {
                return ResourceManager.GetString("UserPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and re-type password are not match.
        /// </summary>
        internal static string UserPasswordNotMatch {
            get {
                return ResourceManager.GetString("UserPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials. You have {0} more attempt(s) before your account gets locked out.
        /// </summary>
        internal static string UserSignInAttemptsLeft {
            get {
                return ResourceManager.GetString("UserSignInAttemptsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to login. Please contact your administrator.
        /// </summary>
        internal static string UserUnAuthorized {
            get {
                return ResourceManager.GetString("UserUnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been unlocked successfully.
        /// </summary>
        internal static string UserUnlockSuccessful {
            get {
                return ResourceManager.GetString("UserUnlockSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked due to unusual signin attempts.
        /// </summary>
        internal static string UserUnusualAttempts {
            get {
                return ResourceManager.GetString("UserUnusualAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username varification is succeded.
        /// </summary>
        internal static string UserVerifiedUserName {
            get {
                return ResourceManager.GetString("UserVerifiedUserName", resourceCulture);
            }
        }
    }
}
